# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '地址管理',
                'verbose_name_plural': '地址管理',
                'db_table': 'addressinfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djoncharts.AddressInfo')),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
                'db_table': 'userinfo',
            },
        ),
    ]
