# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djoncharts', '0002_weiboinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronavirus',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('timenow', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=30)),
                ('txt', models.CharField(max_length=300, null=True)),
                ('repost', models.IntegerField(verbose_name=3)),
                ('comment', models.IntegerField(verbose_name=3)),
                ('thumb', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
